#!/usr/bin/env bash
#
# docker/entrypoint.sh — W5Base containerized dev-environment orchestration.
#
# Purpose (AAP 0.5.1 Group 2): deterministically stand up a working W5Base
# instance inside the application container by realizing the documented
# ten-step setup on a modern Debian base. Runs as the container ENTRYPOINT
# (see Dockerfile: ENTRYPOINT ["/opt/w5base/docker/entrypoint.sh"]).
#
# Ordered responsibilities:
#   1. Derive/export runtime environment (never hardcode secrets).
#   2. Create the w5base service account + runtime directories.
#   3. Render the three /etc/w5base config files from docker/w5base/*.tmpl
#      (secrets injected from env at render time only) and materialize the
#      HTTP Basic auth credential file the Apache vhost authenticates against.
#   4. Wait for database readiness, then provision the database + application
#      user with MODERN CREATE USER / GRANT (supersedes legacy INSERT INTO user).
#   5. Build the schema non-interactively via W5Event TableVersionCheck.
#   6. Start the persistent W5Server control plane.
#   7. exec Apache in the foreground as the container's main process.
#
# CONSTRAINTS honored:
#   - This SCRIPT contains NO hardcoded secrets; all secrets arrive via env.
#   - Idempotent: safe to run on every container (re)start.
#   - References — never edits — the repo's own utilities under sbin/.
#
set -euo pipefail

log() { printf '[entrypoint] %s\n' "$*" >&2; }
die() { printf '[entrypoint][FATAL] %s\n' "$*" >&2; exit 1; }

########################################################################
# 1. Environment derivation (defaults mirror etc/w5base/default.conf +
#    README.txt filesystem layout; only NON-secret values get defaults).
########################################################################
export W5BASEINSTDIR="${W5BASEINSTDIR:-/opt/w5base}"
export W5BASESRVUSER="${W5BASESRVUSER:-w5base}"
export W5BASE_OPERATION_MODE="${W5BASE_OPERATION_MODE:-online}"
W5SRVGROUP="${W5BASESRVGROUP:-daemon}"          # W5ServerGroup default (default.conf)
APACHE_USER="${APACHE_RUN_USER:-www-data}"      # Debian apache user
W5CONFDIR="/etc/w5base"
W5STATEDIR="/var/opt/w5base/state"
W5LOGDIR="/var/log/w5base"
W5SERVER_CONFIG="w5server"                       # -> /etc/w5base/w5server.conf
W5APP_CONFIG="w5base"                            # -> /etc/w5base/w5base.conf

DB_NAME="${MYSQL_DATABASE:-w5base}"
DB_APP_USER="${MYSQL_USER:-w5base}"
DB_APP_PASS="${W5BASE_DB_PASSWORD:-${MYSQL_PASSWORD:-}}"
DB_ROOT_PASS="${MYSQL_ROOT_PASSWORD:-}"

DB_HOST="${W5BASE_DB_HOST:-}"
DB_PORT="${W5BASE_DB_PORT:-}"
if [ -n "${W5BASE_DSN:-}" ]; then
  case "$W5BASE_DSN" in
    *host=*) [ -z "$DB_HOST" ] && DB_HOST="$(printf '%s' "$W5BASE_DSN" | sed -n 's/.*host=\([^;:]*\).*/\1/p')" ;;
  esac
  case "$W5BASE_DSN" in
    *port=*) [ -z "$DB_PORT" ] && DB_PORT="$(printf '%s' "$W5BASE_DSN" | sed -n 's/.*port=\([^;:]*\).*/\1/p')" ;;
  esac
fi
DB_HOST="${DB_HOST:-db}"       # compose service name
DB_PORT="${DB_PORT:-3306}"

log "INSTDIR=$W5BASEINSTDIR SRVUSER=$W5BASESRVUSER DB=$DB_APP_USER@$DB_HOST:$DB_PORT/$DB_NAME mode=$W5BASE_OPERATION_MODE"

# Write a SECRET-FREE /etc/profile.local so interactive `docker exec` shells
# and the repo's shell-entry scripts inherit INSTDIR/service context.
umask 022
cat > /etc/profile.local <<EOF
# Generated by docker/entrypoint.sh — SECRET-FREE (no passwords here).
export W5BASEINSTDIR="$W5BASEINSTDIR"
export W5BASESRVUSER="$W5BASESRVUSER"
export W5BASE_OPERATION_MODE="$W5BASE_OPERATION_MODE"
EOF

########################################################################
# 2. Service account + runtime directories (idempotent).
#    Mirrors README.txt L215-L240 (install -m 2770 -o w5base -g daemon ...).
########################################################################
if ! getent group "$W5SRVGROUP" >/dev/null 2>&1; then
  groupadd --system "$W5SRVGROUP"
fi
if ! id "$W5BASESRVUSER" >/dev/null 2>&1; then
  useradd --system --home-dir "$W5BASEINSTDIR" --no-create-home \
          --shell /usr/sbin/nologin --gid "$W5SRVGROUP" "$W5BASESRVUSER"
  log "created service account $W5BASESRVUSER"
fi
# Apache (www-data) must share the w5base group to read 2770 config + write logs.
if id "$APACHE_USER" >/dev/null 2>&1; then
  usermod -aG "$W5SRVGROUP" "$APACHE_USER" || true
fi

for d in "$W5CONFDIR" /var/opt/w5base "$W5STATEDIR" "$W5LOGDIR"; do
  install -d -m 2770 -o "$W5BASESRVUSER" -g "$W5SRVGROUP" "$d"
done
log "runtime directories ready"

########################################################################
# 3. Render config templates -> /etc/w5base (secrets injected from env only).
########################################################################
TMPL_DIR="$W5BASEINSTDIR/docker/w5base"
# shellcheck disable=SC2016  # literal ${VAR} names are intentional: passed to envsubst
ENVSUBST_VARS='${W5BASE_DSN} ${W5BASE_DB_PASSWORD} ${W5BASE_ADMIN} ${W5BASE_OPERATION_MODE} ${W5BASESRVUSER} ${SITENAME} ${AutoLoadMenuPath}'

render_tmpl() {
  src="$1"; dst="$2"
  [ -f "$src" ] || die "missing template: $src"
  envsubst "$ENVSUBST_VARS" < "$src" > "$dst"
  chown "$W5BASESRVUSER:$W5SRVGROUP" "$dst"
  chmod 0640 "$dst"      # contains DB password -> not world-readable
  log "rendered $(basename "$dst")"
}
render_tmpl "$TMPL_DIR/databases.conf.tmpl" "$W5CONFDIR/databases.conf"
render_tmpl "$TMPL_DIR/w5server.conf.tmpl"  "$W5CONFDIR/w5server.conf"
render_tmpl "$TMPL_DIR/w5base.conf.tmpl"    "$W5CONFDIR/w5base.conf"

# --- Materialize the HTTP Basic auth credential file (part of step 3) --------
# The Apache vhost (docker/apache/w5base.conf) authenticates /w5base/auth against
# 'AuthUserFile /etc/w5base/htpasswd'. That vhost documents this file as written
# at runtime here from ${W5BASE_ADMIN}/${W5BASE_ADMIN_PASSWORD}, and the
# Basic-auth username MUST equal MASTERADMIN (=${W5BASE_ADMIN}) so the kernel
# elevates the authenticated REMOTE_USER to admin and the main menu renders at
# /w5base/auth/base/menu/root. Credentials are read from the environment ONLY
# (never hardcoded); the password is piped via STDIN so it never appears in the
# process list (same posture as MYSQL_PWD below). The file is group-readable by
# Apache — www-data was added to the w5base group in step 2.
[ -n "${W5BASE_ADMIN:-}" ] || die "W5BASE_ADMIN must be set to create the Basic-auth file"
[ -n "${W5BASE_ADMIN_PASSWORD:-}" ] || die "W5BASE_ADMIN_PASSWORD must be set to create the Basic-auth file"
W5HTPASSWD="$W5CONFDIR/htpasswd"
if command -v htpasswd >/dev/null 2>&1; then
  # -c create, -B bcrypt, -i read password from STDIN (keeps it out of ps).
  printf '%s' "$W5BASE_ADMIN_PASSWORD" | htpasswd -c -B -i "$W5HTPASSWD" "$W5BASE_ADMIN"
else
  # Fallback when apache2-utils is unavailable: Apache-compatible APR1 (MD5) hash.
  printf '%s:%s\n' "$W5BASE_ADMIN" \
    "$(printf '%s' "$W5BASE_ADMIN_PASSWORD" | openssl passwd -apr1 -stdin)" > "$W5HTPASSWD"
fi
chown "$W5BASESRVUSER:$W5SRVGROUP" "$W5HTPASSWD"
chmod 0640 "$W5HTPASSWD"
log "wrote HTTP Basic auth file for admin user '$W5BASE_ADMIN'"

########################################################################
# 4. Wait for DB readiness, then modern CREATE USER / GRANT (idempotent).
#    Compose already gates on service_healthy; this is defence-in-depth.
########################################################################
log "waiting for database at $DB_HOST:$DB_PORT ..."
tries=0
until mysqladmin ping -h "$DB_HOST" -P "$DB_PORT" --silent >/dev/null 2>&1; do
  tries=$((tries + 1))
  [ "$tries" -ge 60 ] && die "database not reachable after $tries attempts"
  sleep 2
done
log "database is reachable"

if [ -n "$DB_ROOT_PASS" ]; then
  # MYSQL_PWD avoids leaking the password via the process list (ps).
  # Grants are SCOPED to the application schema only (least privilege).
  MYSQL_PWD="$DB_ROOT_PASS" mysql -h "$DB_HOST" -P "$DB_PORT" -u root <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4;
CREATE USER IF NOT EXISTS '${DB_APP_USER}'@'%' IDENTIFIED BY '${DB_APP_PASS}';
ALTER USER '${DB_APP_USER}'@'%' IDENTIFIED BY '${DB_APP_PASS}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER,
      CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE,
      CREATE VIEW, SHOW VIEW, REFERENCES
  ON \`${DB_NAME}\`.* TO '${DB_APP_USER}'@'%';
FLUSH PRIVILEGES;
SQL
  log "database/user provisioned via modern CREATE USER/GRANT"
else
  log "MYSQL_ROOT_PASSWORD not set; assuming DB image already provisioned user/db"
fi

########################################################################
# 5. Non-interactive schema build (reconcile sql/ against live DB).
#    README.txt L456. -s serverless so it does NOT require W5Server yet.
########################################################################
cd "$W5BASEINSTDIR"
log "running TableVersionCheck (schema build) ..."
"$W5BASEINSTDIR/sbin/W5Event" -c "$W5APP_CONFIG" -s -d -v TableVersionCheck
log "schema build complete"

########################################################################
# 6. Start the persistent W5Server control plane (daemonizes, self-drops
#    privileges to W5ServerUser/Group). Remove stale pidfile for idempotency.
########################################################################
rm -f "$W5STATEDIR/W5Server.${W5SERVER_CONFIG}.pid"
log "starting W5Server ..."
"$W5BASEINSTDIR/sbin/W5Server" -c "$W5SERVER_CONFIG"
log "W5Server started"

########################################################################
# 7. Hand off to Apache in the foreground (container main process).
########################################################################
log "starting Apache (prefork + mod_perl2) in foreground"
: "${APACHE_RUN_DIR:=/var/run/apache2}"
install -d -m 0755 "${APACHE_RUN_DIR}" 2>/dev/null || true
exec apache2ctl -D FOREGROUND
